// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr6xjHabDnGO4ZOViY2jIOYWyucNRWRqc',
    appId: '1:460417444897:web:3fae82a78d525a34470760',
    messagingSenderId: '460417444897',
    projectId: 'pasaportemisionerovirtual',
    authDomain: 'pasaportemisionerovirtual.firebaseapp.com',
    storageBucket: 'pasaportemisionerovirtual.firebasestorage.app',
    measurementId: 'G-5DRN1TFCK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwE1fwXoTBKttsdbQU9iySh3RnoFMvbg',
    appId: '1:460417444897:android:c3881f86673176b8470760',
    messagingSenderId: '460417444897',
    projectId: 'pasaportemisionerovirtual',
    storageBucket: 'pasaportemisionerovirtual.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGx1S1YM3G_5SuMQcrTxtTUQLWS9aDG9U',
    appId: '1:460417444897:ios:8d75b7f1e4d7259a470760',
    messagingSenderId: '460417444897',
    projectId: 'pasaportemisionerovirtual',
    storageBucket: 'pasaportemisionerovirtual.firebasestorage.app',
    iosBundleId: 'com.cmo.pasaporteMisioneroCmo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGx1S1YM3G_5SuMQcrTxtTUQLWS9aDG9U',
    appId: '1:460417444897:ios:8d75b7f1e4d7259a470760',
    messagingSenderId: '460417444897',
    projectId: 'pasaportemisionerovirtual',
    storageBucket: 'pasaportemisionerovirtual.firebasestorage.app',
    iosBundleId: 'com.cmo.pasaporteMisioneroCmo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr6xjHabDnGO4ZOViY2jIOYWyucNRWRqc',
    appId: '1:460417444897:web:386974ea37f9b840470760',
    messagingSenderId: '460417444897',
    projectId: 'pasaportemisionerovirtual',
    authDomain: 'pasaportemisionerovirtual.firebaseapp.com',
    storageBucket: 'pasaportemisionerovirtual.firebasestorage.app',
    measurementId: 'G-0BRYZLKL96',
  );
}
